### ISSUE TITLE
error means what? i'm using centos 6

### ISSUE THREAD

**Issue by hwongcom** [perl11/p2#28]
[root@localhost p2]# make install
make -f dist.mak install PREFIX="/usr/local"
make[1]: Entering directory `/usr/local/src/p2'
make[1]: *** No rule to make target`bin/p2-s', needed by `pkg/p2-0.0.2105-x86_64-redhat-linux-devel.tar.gz'.  Stop.
make[1]: Leaving directory`/usr/local/src/p2'
make: **\* [install] Error 2

**Comment by rurban** [comment]
It means that the make target for `bin/p2-s` is missing, the statically compiled p2. 
Does `make static install` help? It works for me
