### ISSUE TITLE
Two questions on p2

### ISSUE THREAD

**Issue by capstar** [perl11/p2#29]
I am a perl user.  Really excited the performance of p2.  Wonder how to get the milissecond timestamp

When I run the following code snippet, got error.  Wonder why.  Thanks!
```
** Internal parser error: Couldn't parse all statements before text "::HiRes qw( gettimeofday);" at perf01.pl:1
```

here is the code snippet:

```
use Time::HiRes qw( gettimeofday);

sub getTS {
	my ($seconds, $microseconds) = gettimeofday;
	return $seconds + (0.0+ $microseconds)/1000000.0;
}


$start = getTS();
$i = 0;
while ($i < 1000000) {
	$i += 1;
}
printf("took %f secs\n", getTS() - $start);
```

**Comment by rurban** [comment]
1. You get milliseconds timestamps from outside via `date +%s%N |cut -c1-16` or native calls (different on linux and darwin).

2. p2 cannot load perl XS modules. you need to time it externally. there's no bench module yet.
on linux perf stat is best.

`bin/p2 -e'$i=0;while ($i < 1000000) { $i++ }'`

**Comment by capstar** [comment]
Thanks.  I used "time" command to time it and found it to be 6 times faster than running on perl. 

Wish perl could have a restricted mode where we lose sometime (like be able to change the variable type after it's initialization) and gains lots of speed.

**Comment by rurban** [comment]
perl5 is not really optimizable without a total rewrite. It's not only the bad optree and vm run-time design, it's also the data structures and the memory refcounting scheme. even with a better optree as in ruby or python you don't get much more speed.

see the cperl docs and todo list. I'm working on it:
https://github.com/perl11/cperl/blob/master/pod/perlcperl.pod#longer-term-goals

method inlining, native ops and a simple jit should help a bit.
